# Generated by Django 5.2.9 on 2025-12-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The main content/question/idea')),
                ('category', models.CharField(choices=[('date', 'Date Idea'), ('convo', 'Conversation'), ('wyr', 'Would You Rather'), ('game', 'Quick Game')], db_index=True, help_text='Type of spark', max_length=20)),
                ('option_b', models.TextField(blank=True, default='', help_text='For WYR: the second option (leave blank for other categories)')),
                ('vibe', models.CharField(choices=[('wholesome', 'Wholesome'), ('lore', 'The Lore'), ('chaos', 'Chaos Mode'), ('spicy', 'Spicy'), ('grind', 'The Grind'), ('plot', 'The Plot'), ('intellectual', 'Big Brain'), ('wildcard', 'Wildcard')], db_index=True, default='wildcard', help_text='Mood/tone of this spark (wholesome, spicy, chaos, etc.)', max_length=20)),
                ('subtitle', models.CharField(blank=True, default='', help_text='Optional brief subtitle or instruction', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Spark',
                'verbose_name_plural': 'Sparks',
            },
        ),
    ]
