# Generated by Django 5.2.9 on 2025-12-30 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_spark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='reactivation_requested_by',
            field=models.ForeignKey(blank=True, help_text='User who requested to reactivate this ended relationship', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactivation_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
