# Generated by Django 5.2.9 on 2025-12-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_couple_reactivation_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='timezone',
            field=models.CharField(default='UTC', help_text="Shared timezone for determining daily prompts (both users see same 'today')", max_length=50),
        ),
    ]
