# Generated by Django 5.2.9 on 2025-12-30 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_couple_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SparkPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(db_index=True, default=False, help_text='Hide this spark from random selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='core.spark')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spark_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spark Preference',
                'verbose_name_plural': 'Spark Preferences',
                'unique_together': {('user', 'spark')},
            },
        ),
    ]
